# C64 NonSense, just playing around with C64 cross-compile tools.
# Copyright (C) 2020  Dirk "YouDirk" Lehmann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


name: CI

on:
  push:
    branches:
    - 'master'
    paths:
    - '**'
  pull_request:
    branches:
    - 'master'
    paths:
    - '**'

# Settings
env:
  # ${{secrets.RELEASE_TOKEN}}
  WORKFL_SRC_PATH:                 'src'
  WORKFL_DOCKER_USER:              'YouDirk'

# Jobs are running in parallel
jobs:
  compile-linux:
    name: Compiles on Linux
    runs-on: ubuntu-latest
    steps:
      # Checking out to $GITHUB_WORKSPACE
    - name: Checking out...
      uses: actions/checkout@v2.3.4
      with:
        clean: true
        lfs: false
        submodules: false
    - name: Initialzing Docker cache...
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{env.WORKFL_DOCKER_USER}}
        password: ${{secrets.RELEASE_TOKEN}}
        registry: docker.pkg.github.com
        image_name: cc65+vice-environment
        context: ./.github/actions/cc65+vice-environment
    - name: Compiling with Default config, using `$> make all`...
      uses: ./.github/actions/cc65+vice-environment
      with:
        exec: make all
    - name: Compiling with Productive config, using `$> make recompile`...
      uses: ./.github/actions/cc65+vice-environment
      with:
        exec: make DEBUG_BUILD=0 recompile
    - name: Compiling with Full Debug config, using `$> make recompile`...
      uses: ./.github/actions/cc65+vice-environment
      with:
        exec: make DEBUG_BUILD=all recompile

  publish-latest:
    if: ${{github.event_name == 'push'}}
    name: Publishing 'Latest Commit' release...
    needs: [compile-linux]
    runs-on: ubuntu-latest
    steps:
      # Checking out to $GITHUB_WORKSPACE
    - name: Checking out...
      uses: actions/checkout@v2.3.4
      with:
        clean: true
        lfs: false
        submodules: false
    - name: Building Debug version, using `$> make all`...
      uses: ./.github/actions/cc65+vice-environment
      with:
        exec: make DEBUG_BUILD=1
              D64EXT=$(echo $GITHUB_SHA | head -c7).debug.d64
              all && cp -f ${{env.WORKFL_SRC_PATH}}/*.d64 .
    - name: Building Productive version, using `$> make recompile`...
      uses: ./.github/actions/cc65+vice-environment
      with:
        exec: make DEBUG_BUILD=0
              D64EXT=$(echo $GITHUB_SHA | head -c7).d64
              recompile && cp -f ${{env.WORKFL_SRC_PATH}}/*.d64 .
    - name: Building Full Debug version, using `$> make recompile`...
      uses: ./.github/actions/cc65+vice-environment
      with:
        exec: make DEBUG_BUILD=all
              D64EXT=$(echo $GITHUB_SHA | head -c7).debug-full.d64
              recompile && cp -f ${{env.WORKFL_SRC_PATH}}/*.d64 .
    - name: Updating TODO ...
      run: |
        ls -R
